spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: ${SECRET_KEY}
  token:
    access-expiration-time: 86400

server:
  servlet:
    session:
      cookie:
        secure:true
        same-site:none
        http-only:false